import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Header from './components/Header/Header'
import Menu from './components/Menu'
import Titulo from './components/Titulo'
import Footer from './components/Footer'
import './globals.css'



const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="back">
      <Header user="Lorem Ipsum" />
      <div className='flex'>
          <Menu user="x" />        
        <div>
          <Titulo textoTitulo="Escritorio" />
          {children}
        </div>
        
      </div>
      <Footer texto='text' />  
        
        </div>
      </body>
    </html>
  )
}
